trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: npm run test:ci
  displayName: 'Run tests'
  env:
    SPAUTH_SITEURL: $(ci.spo.siteurl)
    SPAUTH_CLIENTID: $(ci.spo.clientId)
    SPAUTH_CLIENTSECRET: $(ci.spo.clientSecret)
